# Generated by Django 3.1.4 on 2020-12-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=" My freakin' Awesome blog! ", max_length=255),
        ),
    ]
