# Generated by Django 3.1.4 on 2020-12-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20201226_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='Click link above to read blog post', max_length=255),
        ),
    ]
